"""empty message

Revision ID: ee0c1e6f539b
Revises: 81f95fb58594
Create Date: 2019-09-05 19:46:13.743543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0c1e6f539b'
down_revision = '81f95fb58594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permission')
    op.drop_column('role', 'default')
    # ### end Alembic commands ###
